FROM python:3.12-alpine3.17

WORKDIR /usr/src/app

#Copy usamos los requisitos para instalar las dependencias
COPY requirements.txt requirements.txt 

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "app.py" ]